apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-test-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Zivgl66/Bank_Leumi
    targetRevision: main
    path: ./Kubernetes/
    directory:
      recurse: true
  destination:
    server: https://710986295EBDFD603F7E9E5206FA3899.gr7.us-east-1.eks.amazonaws.com
    namespace: python-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
