apiVersion: v1
kind: Service
metadata:
  name: python-app-clusterip-service
  namespace: python-app
spec:
  selector:
    app: py-app
  ports:
    - name: http
      port: 3333
      targetPort: 3333
      protocol: TCP
  type: ClusterIP
