apiVersion: v1
kind: Service
metadata:
  name: python-app-lb-service
  namespace: python-app
spec:
  type: LoadBalancer
  ports:
    - port: 443
      protocol: TCP
      targetPort: 3333
  selector:
    app: py-app
